<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Booking;

class BookingSeeder extends Seeder
{
    public function run(): void
    {
        $bookings = [
            [
                'name' => 'John Doe',
                'user_id' => 1,
                'package_id' => 1,
                'date' => now()->addDays(30),
                'number_of_adult' => 2,
                'number_of_child' => 0,
                'pick_up_location' => 'Airport',
                'pick_up_location_details' => 'Terminal 2, Gate 5',
                'total_fee' => 4998,
                'total_amount' => 4998,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt1.pdf',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'name' => 'Jane Smith',
                'user_id' => 2,
                'package_id' => 2,
                'date' => now()->addDays(45),
                'number_of_adult' => 2,
                'number_of_child' => 1,
                'pick_up_location' => 'Hotel',
                'pick_up_location_details' => 'Grand Hyatt, Lobby',
                'total_fee' => 5998,
                'total_amount' => 5998,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt2.pdf',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'name' => 'Robert Johnson',
                'user_id' => 3,
                'package_id' => 3,
                'date' => now()->addDays(60),
                'number_of_adult' => 1,
                'number_of_child' => 0,
                'pick_up_location' => 'Airport',
                'pick_up_location_details' => 'Terminal 1, Arrival Hall',
                'total_fee' => 1899,
                'total_amount' => 1899,
                'reservation_status' => 'pending',
                'invoice_status' => 'Unpaid',
                'payment_status' => 'pending',
                'payment_receipt' => null,
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(15),
            ],
            [
                'name' => 'Maria Garcia',
                'user_id' => 4,
                'package_id' => 4,
                'date' => now()->addDays(20),
                'number_of_adult' => 3,
                'number_of_child' => 0,
                'pick_up_location' => 'Office',
                'pick_up_location_details' => 'Downtown Business Center',
                'total_fee' => 3897,
                'total_amount' => 3897,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt4.pdf',
                'created_at' => now()->subWeek(),
                'updated_at' => now()->subWeek(),
            ],
            [
                'name' => 'Li Wei',
                'user_id' => 5,
                'package_id' => 5,
                'date' => now()->addDays(90),
                'number_of_adult' => 2,
                'number_of_child' => 2,
                'pick_up_location' => 'Airport',
                'pick_up_location_details' => 'International Terminal',
                'total_fee' => 6598,
                'total_amount' => 6598,
                'reservation_status' => 'pending',
                'invoice_status' => 'Unpaid',
                'payment_status' => 'pending',
                'payment_receipt' => null,
                'created_at' => now()->subWeeks(2),
                'updated_at' => now()->subWeeks(2),
            ],
            [
                'name' => 'Ahmed Hassan',
                'user_id' => 6,
                'package_id' => 6,
                'date' => now()->addDays(75),
                'number_of_adult' => 4,
                'number_of_child' => 0,
                'pick_up_location' => 'Hotel',
                'pick_up_location_details' => 'Hilton Resort, Main Entrance',
                'total_fee' => 7196,
                'total_amount' => 7196,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt6.pdf',
                'created_at' => now()->subWeeks(3),
                'updated_at' => now()->subWeeks(3),
            ],
            [
                'name' => 'Sophie Martin',
                'user_id' => 7,
                'package_id' => 7,
                'date' => now()->addDays(40),
                'number_of_adult' => 2,
                'number_of_child' => 1,
                'pick_up_location' => 'Airport',
                'pick_up_location_details' => 'Terminal 3, Gate 2',
                'total_fee' => 1498,
                'total_amount' => 1498,
                'reservation_status' => 'Reject',
                'invoice_status' => 'Unpaid',
                'payment_status' => 'Reject',
                'payment_receipt' => null,
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'name' => 'Carlos Rodriguez',
                'user_id' => 8,
                'package_id' => 8,
                'date' => now()->addDays(55),
                'number_of_adult' => 1,
                'number_of_child' => 0,
                'pick_up_location' => 'Hotel',
                'pick_up_location_details' => 'Burj Al Arab, Private Entrance',
                'total_fee' => 2199,
                'total_amount' => 2199,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt8.pdf',
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'name' => 'Emma Wilson',
                'user_id' => 9,
                'package_id' => 9,
                'date' => now()->addDays(120),
                'number_of_adult' => 2,
                'number_of_child' => 0,
                'pick_up_location' => 'Airport',
                'pick_up_location_details' => 'Domestic Terminal',
                'total_fee' => 5598,
                'total_amount' => 5598,
                'reservation_status' => 'pending',
                'invoice_status' => 'Unpaid',
                'payment_status' => 'pending',
                'payment_receipt' => null,
                'created_at' => now()->subWeeks(4),
                'updated_at' => now()->subWeeks(4),
            ],
            [
                'name' => 'Raj Patel',
                'user_id' => 10,
                'package_id' => 10,
                'date' => now()->addDays(80),
                'number_of_adult' => 3,
                'number_of_child' => 2,
                'pick_up_location' => 'Hotel',
                'pick_up_location_details' => 'Bali Paradise Resort, Beach Side',
                'total_fee' => 4497,
                'total_amount' => 4497,
                'reservation_status' => 'Conform',
                'invoice_status' => 'Paid',
                'payment_status' => 'Success',
                'payment_receipt' => 'receipt10.pdf',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
        ];

        foreach ($bookings as $booking) {
            Booking::create($booking);
        }
    }
}
