<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\travelPackage;

class TravelPackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'package_name' => 'Swiss Alps Adventure Trek',
                'tour_type' => 'Adventure Tour',
                'price_start_from' => 2499,
                'duration' => 7,
                'overview' => 'Experience the breathtaking beauty of the Swiss Alps with our comprehensive adventure trek. This 7-day journey takes you through pristine mountain landscapes, charming alpine villages, and offers thrilling outdoor activities.',
                'included_things' => 'Mountain guide, accommodation, meals, equipment rental, insurance, transportation',
                'Excludes_things' => 'Personal expenses, travel insurance, optional activities',
                'tour_plane_description' => 'Day 1: Arrival in Zurich, Day 2: Transfer to Interlaken, Day 3: Hiking to Jungfraujoch, Day 4: Adventure activities, Day 5: Explore Grindelwald, Day 6: Free day, Day 7: Departure',
                'per_adult_fee' => 2499.00,
                'per_child_fee' => 1249.00,
                'image_1' => 'swiss1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'package_name' => 'Maldives Luxury Beach Resort',
                'tour_type' => 'Beach Holiday Tour',
                'price_start_from' => 3999,
                'duration' => 5,
                'overview' => 'Indulge in ultimate luxury at our exclusive Maldives beach resort. Crystal clear waters, pristine beaches, and world-class amenities await you in this tropical paradise.',
                'included_things' => 'Luxury villa accommodation, all meals, water sports, spa access, airport transfers',
                'Excludes_things' => 'International flights, premium alcohol, personal shopping',
                'tour_plane_description' => 'Day 1: Arrival and check-in, Day 2: Island hopping, Day 3: Water sports day, Day 4: Spa and relaxation, Day 5: Departure',
                'per_adult_fee' => 3999.00,
                'per_child_fee' => 1999.00,
                'image_1' => 'maldives1.jpg',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'package_name' => 'Japan Cultural Heritage Tour',
                'tour_type' => 'Cultural Tour',
                'price_start_from' => 1899,
                'duration' => 10,
                'overview' => 'Immerse yourself in Japan\'s rich cultural heritage. From ancient temples to modern cities, experience the perfect blend of tradition and innovation.',
                'included_things' => 'Accommodation, guided tours, temple visits, cultural experiences, some meals',
                'Excludes_things' => 'International flights, most meals, personal expenses',
                'tour_plane_description' => 'Day 1-2: Tokyo, Day 3-4: Kyoto, Day 5-6: Osaka, Day 7-8: Nara, Day 9-10: Return to Tokyo and departure',
                'per_adult_fee' => 1899.00,
                'per_child_fee' => 949.00,
                'image_1' => 'japan1.jpg',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'package_name' => 'Singapore Business & Leisure',
                'tour_type' => 'Business Trip Tour',
                'price_start_from' => 1299,
                'duration' => 4,
                'overview' => 'Perfect blend of business meetings and leisure activities in modern Singapore. Experience efficient business environment and world-class entertainment.',
                'included_things' => 'Business center access, city tours, accommodation, breakfast',
                'Excludes_things' => 'Business meeting fees, most meals, personal expenses',
                'tour_plane_description' => 'Day 1: Business meetings, Day 2: City tour, Day 3: Sentosa Island, Day 4: Departure',
                'per_adult_fee' => 1299.00,
                'per_child_fee' => 649.00,
                'image_1' => 'singapore1.jpg',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'package_name' => 'Safari Adventure Kenya',
                'tour_type' => 'Adventure Tour',
                'price_start_from' => 3299,
                'duration' => 8,
                'overview' => 'Experience the ultimate African safari adventure in Kenya. Witness the Big Five in their natural habitat and enjoy the breathtaking landscapes.',
                'included_things' => 'Safari drives, accommodation, meals, park fees, guide services',
                'Excludes_things' => 'International flights, travel insurance, tips',
                'tour_plane_description' => 'Day 1: Nairobi, Day 2-3: Maasai Mara, Day 4-5: Lake Nakuru, Day 6-7: Amboseli, Day 8: Departure',
                'per_adult_fee' => 3299.00,
                'per_child_fee' => 1649.00,
                'image_1' => 'kenya1.jpg',
                'created_at' => now()->subWeek(),
                'updated_at' => now()->subWeek(),
            ],
            [
                'package_name' => 'Greek Islands Hopping',
                'tour_type' => 'Beach Holiday Tour',
                'price_start_from' => 1799,
                'duration' => 9,
                'overview' => 'Discover the magic of the Greek islands. From ancient history to stunning beaches, experience the best of Greek island life.',
                'included_things' => 'Ferry tickets, accommodation, breakfast, island tours',
                'Excludes_things' => 'International flights, most meals, personal expenses',
                'tour_plane_description' => 'Day 1: Athens, Day 2-3: Mykonos, Day 4-5: Santorini, Day 6-7: Crete, Day 8: Return to Athens, Day 9: Departure',
                'per_adult_fee' => 1799.00,
                'per_child_fee' => 899.00,
                'image_1' => 'greece1.jpg',
                'created_at' => now()->subWeeks(2),
                'updated_at' => now()->subWeeks(2),
            ],
            [
                'package_name' => 'India Golden Triangle',
                'tour_type' => 'Cultural Tour',
                'price_start_from' => 999,
                'duration' => 6,
                'overview' => 'Explore India\'s most famous cultural triangle. Delhi, Agra, and Jaipur offer an incredible journey through Indian history and culture.',
                'included_things' => 'Accommodation, transportation, guided tours, monument fees',
                'Excludes_things' => 'International flights, most meals, personal expenses',
                'tour_plane_description' => 'Day 1-2: Delhi, Day 3: Agra (Taj Mahal), Day 4-5: Jaipur, Day 6: Return to Delhi and departure',
                'per_adult_fee' => 999.00,
                'per_child_fee' => 499.00,
                'image_1' => 'india1.jpg',
                'created_at' => now()->subWeeks(3),
                'updated_at' => now()->subWeeks(3),
            ],
            [
                'package_name' => 'Dubai Luxury Experience',
                'tour_type' => 'Business Trip Tour',
                'price_start_from' => 2199,
                'duration' => 5,
                'overview' => 'Experience the luxury and innovation of Dubai. Perfect for business travelers who want to experience the best of modern UAE.',
                'included_things' => 'Luxury accommodation, business center access, city tours, breakfast',
                'Excludes_things' => 'International flights, business expenses, most meals',
                'tour_plane_description' => 'Day 1: Business meetings, Day 2: City tour, Day 3: Desert safari, Day 4: Shopping and leisure, Day 5: Departure',
                'per_adult_fee' => 2199.00,
                'per_child_fee' => 1099.00,
                'image_1' => 'dubai1.jpg',
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'package_name' => 'Norway Fjords Exploration',
                'tour_type' => 'Adventure Tour',
                'price_start_from' => 2799,
                'duration' => 7,
                'overview' => 'Discover the stunning Norwegian fjords. Experience dramatic landscapes, midnight sun, and authentic Scandinavian culture.',
                'included_things' => 'Fjord cruise, accommodation, meals, guided tours, transportation',
                'Excludes_things' => 'International flights, personal expenses, optional activities',
                'tour_plane_description' => 'Day 1: Oslo, Day 2-3: Bergen and fjords, Day 4-5: Flåm Railway, Day 6: Stavanger, Day 7: Departure',
                'per_adult_fee' => 2799.00,
                'per_child_fee' => 1399.00,
                'image_1' => 'norway1.jpg',
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'package_name' => 'Bali Paradise Retreat',
                'tour_type' => 'Beach Holiday Tour',
                'price_start_from' => 1499,
                'duration' => 6,
                'overview' => 'Relax and rejuvenate in beautiful Bali. Experience perfect beaches, ancient temples, and warm Indonesian hospitality.',
                'included_things' => 'Resort accommodation, daily breakfast, airport transfers, temple visits',
                'Excludes_things' => 'International flights, most meals, personal expenses',
                'tour_plane_description' => 'Day 1: Arrival, Day 2: Ubud cultural tour, Day 3: Beach day, Day 4: Temple visits, Day 5: Spa day, Day 6: Departure',
                'per_adult_fee' => 1499.00,
                'per_child_fee' => 749.00,
                'image_1' => 'bali1.jpg',
                'created_at' => now()->subMonth(),
                'updated_at' => now()->subMonth(),
            ],
            [
                'package_name' => 'Egypt Ancient Wonders',
                'tour_type' => 'Cultural Tour',
                'price_start_from' => 1199,
                'duration' => 8,
                'overview' => 'Journey through ancient Egyptian history. From pyramids to pharaohs, experience the wonders of one of the world\'s oldest civilizations.',
                'included_things' => 'Accommodation, guided tours, Nile cruise, monument fees',
                'Excludes_things' => 'International flights, most meals, personal expenses',
                'tour_plane_description' => 'Day 1-2: Cairo and pyramids, Day 3-4: Nile cruise to Luxor, Day 5-6: Aswan, Day 7: Return to Cairo, Day 8: Departure',
                'per_adult_fee' => 1199.00,
                'per_child_fee' => 599.00,
                'image_1' => 'egypt1.jpg',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'package_name' => 'New York Business Gateway',
                'tour_type' => 'Business Trip Tour',
                'price_start_from' => 3499,
                'duration' => 5,
                'overview' => 'Experience the business capital of the world. Perfect combination of business opportunities and iconic New York experiences.',
                'included_things' => 'Business accommodation, meeting room access, city tours, Broadway show',
                'Excludes_things' => 'International flights, business expenses, most meals',
                'tour_plane_description' => 'Day 1: Business meetings, Day 2: Wall Street tour, Day 3: Business networking, Day 4: City highlights, Day 5: Departure',
                'per_adult_fee' => 3499.00,
                'per_child_fee' => 1749.00,
                'image_1' => 'newyork1.jpg',
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subMonths(2),
            ],
        ];

        foreach ($packages as $package) {
            travelPackage::create($package);
        }
    }
}
